name: "test"
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: test
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            npm ci
            npm test

  test-run:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            npm ci
            npm run build

      - name: test run
        uses: ./
        with:
          url: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/tests/fixture/feed.xml"
          file: "tests/fixture/input.md"

      - name: check diff
        run: diff tests/fixture/input.md tests/fixture/wants.md

  conclude:
    runs-on: ubuntu-latest
    needs:
      - test-unit
      - test-run
    if: always()
    permissions:
      actions: read
    steps:
      - uses: sarisia/actions/conclusion@main
        id: ghapi

      - name: report result
        uses: sarisia/actions-status-discord@6712a17f7d0531d44cd42ca2a878b0bdfd07b62a
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.ghapi.outputs.conclusion }}
          title: ${{ github.workflow }} - conclusion
