name: "test"
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: test (should fail)

  test-icu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '12.13'
      - run: npm ci
      - run: npm i icu4c-data@64l
      - run: npm test
        env:
          NODE_ICU_DATA: ./node_modules/icu4c-data
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: test-icu
          
  release-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run release
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: release test
