name: release-branch-test
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - release/*

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          url: 'https://note.sarisia.cc/index.xml'
          file: 'README.md'
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: run-checkout
  run-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sarisia/actions-readme-feed@release/v1
        with:
          url: 'https://note.sarisia.cc/index.xml'
          file: 'README.md'
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: run-branch
