name: "test"
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: test
        uses: devcontainers/ci@e4d707078cd9a8923e188288c13a787d3cd324b9
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            npm ci
            npm test

  test-run:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build
        uses: devcontainers/ci@e4d707078cd9a8923e188288c13a787d3cd324b9
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            npm ci
            npm run build

      - name: test run
        uses: ./
        with:
          url: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/tests/fixture/feed.xml"
          file: "tests/fixture/input.md"

      - name: check diff
        run: diff tests/fixture/input.md tests/fixture/wants.md

  conclude:
    runs-on: ubuntu-latest
    needs:
      - test-unit
      - test-run
    if: always()
    permissions:
      actions: read
    steps:
      - uses: sarisia/actions/conclusion@main
        id: ghapi

      - name: report result
        uses: sarisia/actions-status-discord@9d12cc6d7c8d55f9cbe5efa643117f8c7423f4cf
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.ghapi.outputs.conclusion }}
          title: ${{ github.workflow }} - conclusion
